config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  resources :dreams, except: [:edit, :update, :destroy] do
    resources :locations, only: [:new, :create]
  end
  resources :locations, only: [:index, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/dream.rb
class Dream < ApplicationRecord
  belongs_to :category
  belongs_to :user
  has_many :locations
  has_one_attached :photo

  validates :name, presence: { message: "Ton rêve serait meilleur avec un nom!" }, uniqueness: true, length: { minimum: 5 }
  validates :price, presence: true, numericality: { only_integer: true}
  validates :duration, presence: true, numericality: { only_integer: true }
  validates :description, presence: { message: "Une petite description aiderait ton rêve à être choisi!" }, uniqueness: true, length: { minimum: 10 }

end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :dream
  belongs_to :user

  enum status: {
    En_attente: 0,
    Confirmé: 1,
    Refusé: 2

  }

  validates :comment, presence: true, length: { minimum: 10 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :locations
  has_many :dreams
  has_many :locations_as_owner, through: :dreams, source: :locations
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dreams_controller.rb
class DreamsController < ApplicationController
  def index
    @dreams = Dream.all
  end

  def show
    @dream = Dream.find(params[:id])
  end

  def new
    @dream = Dream.new
  end

  def create
    @dream = Dream.new(dream_params)
    @dream.user = current_user
    if @dream.save
      redirect_to dream_path(@dream)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def dream_params
    params.require(:dream).permit(:name, :description, :price, :duration, :category_id, :photo)
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  def index
    @locations = Location.all
    @user = current_user
  end

  def new
    @dream = Dream.find(params[:dream_id])
    @location = Location.new
  end

  def create
    @location = Location.new(location_params)
    @dream = Dream.find(params[:dream_id])
    @location.dream = @dream
    @location.user = current_user

    if @location.save
      redirect_to locations_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @location = Location.find(params[:id])
    if params[:status].present?
      @location.update(status: params[:status])
      @location.save
      redirect_to locations_path, notice: "Your rental was successfully updated."
    end
  end

  private

  def location_params
    params.require(:location).permit(:comment, :status)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @dream = Dream.find_by(name: "J'ai perdu mes dents")
    @dreamTwo = Dream.find_by(name: "Noël avec Mariah Carey")
    @dreamThree = Dream.find_by(name: "Mariage avec un chat")

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dreams/_dream.html.erb
<%# <div id="<%= dom_id dream %>

<div class="card">

         <%= dream.photo.attached? ? cl_image_tag(dream.photo.key, width: 350, height: 200, crop: :fill, class:"card-img-top")  : image_tag("https://images.unsplash.com/photo-1536893827774-411e1dc7c902?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=464&q=80")%></div>
          <div class="text">
            <p>
              <strong>Catégorie:</strong>
              <%= dream.category.name %>
            </p>
            <p>
              <strong>Titre:</strong>
              <%= dream.name %>
            </p>
            <p>
              <strong>Prix:</strong>
              <%= dream.price%> $
            </p>
          </div>

        <%= link_to "Détails", dream, class:"btn btn-primary" %>

  </div>

<%# </div> %>

app/views/dreams/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="banner_index" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('https://res.cloudinary.com/dvw6upciw/image/upload/v1670006549/banner-image_mrnrg3.jpg)"><h1 class="all-dream">Tous nos rêves</h1></div>

  <div class= "container">

    <div class="row row-cols-1 row-cols-md-3 g-4">
        <% @dreams.each do |dream| %>
        <div class="col">
        <div class="card rounded">
           <%= render dream %>
        </div>
        <% end %>
    </div>
  </div>
</div>

app/views/dreams/new.html.erb
<div class="head">

    <div class="container py-5">
      <div class="row">
        <div class="col-12 col-md-6 offset-lg-3">
          <div class="bg-white rounded p-3 shadow">
            <h2><strong>Ajouter votre rêve</strong></h2>
            <%= simple_form_for @dream do |f| %>
              <%= f.input :name, placeholder: 'Nom de votre rêve' %>
              <%# <%= f.input :photo, as: :file %>
              <%= f.input :description, placeholder: 'Décrivez votre rêve' %>
              <%= f.input :price, placeholder: 'Le prix de votre rêve' %>
              <%= f.input :duration, placeholder: 'Durée de votre rêve '%>
              <%=f.association :category%>
              <%= f.input :photo, as: :file %>
              <input class="btn btn-primary" type="submit" value="Soumettre">
              <%= link_to 'Retour', dreams_path, class: "btn btn-primary" %>
            <% end %>
          </div>
        </div>
      </div>
  </div>
</div>

app/views/dreams/show.html.erb
<br>
<div class="container">

  <h1>Détails</h1>

  <div class="card-product">
  <%= cl_image_tag @dream.photo.key, height: 300, width: 400, crop: :fill%>
    <div class="card-product-infos">
      <h2><%= @dream.name %></h2>
      <p><strong>Categorie</strong></p>
      <p><%= @dream.category.name %></p>
      <p><strong>Description</strong></p>
      <p><%= @dream.description %></p>
      <p><strong>Prix</strong></p>
      <p><%= @dream.price %>$</p>
      <p><strong>Durée</strong></p>
      <p><%= @dream.duration %>min</p>
    </div>
  </div>
<%= link_to 'Je veux ce rêve', new_dream_location_path(@dream), class: "btn btn-primary"%>
    <%= link_to 'Retour', dreams_path, class: "btn btn-primary" %>
    <%= link_to 'Home', root_path, class: "btn btn-primary" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Airdreamndream</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>


  <body class="min-vh-100">
   <p class="notice"><%= notice %></p>

   <p class="alert"><%= alert %></p>
   <%= render "shared/navbar" %>
   <%= render "shared/flashes" %>
   <div class="min-vh-100">
    <%= yield %>
    </div>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/locations/_location.html.erb
  <%= cl_image_tag(location.dream.photo.key) %>
  <div class="card-product-infos">
    <p>
      <strong>Titre</strong>
      <%= location.dream.name %>
    </p>
    <p>
      <strong>Commentaire:</strong>
      <%= location.comment %>
    </p>
    <p>
      <strong>Vendeur</strong>
      <%= location.dream.user.email %>
    </p>
    <p>
      <h2><strong>Status :</strong>
      <%= location.status %></h2>
    </p>
  </div>
<div id="<%= dom_id location %>">
</div>

app/views/locations/_rent.html.erb
  <%= cl_image_tag(location_as_owner.dream.photo.key) %>
  <div class="card-product-infos">
    <p>
      <strong>Commentaire:</strong>
      <%= rent.comment %>
    </p>
    <p>
      <strong>User:</strong>
      <%= rent.user.email %>
    </p>
    <p>
      <strong>Status:</strong>
      <%= rent.status %>
    </p>
</div>

app/views/locations/index.html.erb
<div class="container">
<h1>Rêves que je veux louer</h1>

  <div id="locations">
    <% if @user.locations.empty? %>
    <div class="placeholder"></div>
    <%else %>
    <% @user.locations.each do |location| %>
    <div class="card-product">
      <%= render location %>
    </div>
    <% end %>
  <% end %>
  </div>
</div>
  <div class="container">
  <h1>Mes rêves à louer</h1>


  <div id="rental">
    <% if @user.locations_as_owner.empty? %>
    <div class="placeholder"></div>
     <%else %>
    <% @user.locations_as_owner.each do |rent| %>
    <div class="card-product">
      <%= render rent %>
    </div>
        <% rent.user != @user %>
          <%=link_to "Accepter", location_path(rent, status:'Confirmé'), data:{turbo_method: :patch}, class:"btn btn-primary", :onclick=>'myFunction()'%>
          <%=link_to "Refuser", location_path(rent, status:'Refusé'), data:{turbo_method: :patch}, class:"btn btn-primary", :onclick=>'refuser()'%>
            <script>
              function myFunction() {
              alert("Vous avez acceptez la location");
            }
            </script>

            <script>
              function refuser() {
              alert ("Vous avez rejetez la location");
              }
            </script>
    <% end %>
    <% end %>

  </div>
</div>

app/views/locations/new.html.erb
<div class="min-vh-100">
<div class="row comments ">
<div class="col-12 col-md-6 offset-lg-3 mt-5">
  <div class = "bg-white rounded p-3 shadow">
    <h1>Louez ce rêve</h1>
      <%= simple_form_for ([@dream, @location]) do |f| %>
        <%= f.input :comment %>
        <%= f.button :submit, value="Soumettre", class:"btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>
</div>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1532099514109-7d2d71629d82?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80);">
  <div class="container">
    <h1>Louez le rêve de vos rêves</h1>
    <p>Ne subissez plus vos rêves, prenez le contrôle</p>
    <a class="btn btn-light button" href="dreams">Rêver</a>
  </div>
</div>

<div class="container">
  <h1>Nos rêves les plus populaires </h1>
  <div class="row row-cols-1 row-cols-md-3 g-4">
    <div class="col">
      <div class="card rounded">
        <div class="card">

         <%= @dream.photo.attached? ? cl_image_tag(@dream.photo.key, width: 350, height: 200, crop: :fill, class:"card-img-top")  : image_tag("https://images.unsplash.com/photo-1536893827774-411e1dc7c902?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=464&q=80")%></div>
          <div class="text">
            <p>
              <strong>Catégorie:</strong>
              <% @dream.category.name %>
            </p>
            <p>
              <strong>Titre:</strong>
              <%= @dream.name %>
            </p>
            <p>
              <strong>Prix:</strong>
              <%= @dream.price%> $
            </p>
          </div>

        <%= link_to "Détails", @dream, class:"btn btn-primary" %>
      </div>
    </div>

    <div class="col">
      <div class="card rounded">
        <div class="card">

         <%= @dreamTwo.photo.attached? ? cl_image_tag(@dreamTwo.photo.key, width: 350, height: 200, crop: :fill, class:"card-img-top")  : image_tag("https://images.unsplash.com/photo-1536893827774-411e1dc7c902?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=464&q=80")%></div>
          <div class="text">
            <p>
              <strong>Catégorie:</strong>
              <%= @dreamTwo.category.name %>
            </p>
            <p>
              <strong>Titre:</strong>
              <%= @dreamTwo.name %>
            </p>
            <p>
              <strong>Prix:</strong>
              <%= @dreamTwo.price%> $
            </p>
          </div>

        <%= link_to "Détails", @dreamTwo, class:"btn btn-primary" %>
      </div>
    </div>

     <div class="col">
      <div class="card rounded">
        <div class="card">

         <%= @dreamThree.photo.attached? ? cl_image_tag(@dreamThree.photo.key, width: 350, height: 200, crop: :fill, class:"card-img-top")  : image_tag("https://images.unsplash.com/photo-1536893827774-411e1dc7c902?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=464&q=80")%></div>
          <div class="text">
            <p>
              <strong>Catégorie:</strong>
              <%= @dreamThree.category.name %>
            </p>
            <p>
              <strong>Titre:</strong>
              <%= @dreamThree.name %>
            </p>
            <p>
              <strong>Prix:</strong>
              <%= @dreamThree.price%> $
            </p>
          </div>

        <%= link_to "Détails", @dreamThree, class:"btn btn-primary" %>
      </div>
    </div>
  </div>

</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    Fait avec <i class="fas fa-heart"></i> par la Dream Team
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <img src="https://res.cloudinary.com/dvw6upciw/image/upload/v1669927575/logo_bmgnsi.png">AirDreamnDream
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to 'Home', root_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://img.freepik.com/premium-vector/silhouette-people-walking-rope-with-full-moon-background-illustration_434104-143.jpg?w=2000", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Mes locations", locations_path, class: "dropdown-item" %>
              <%= link_to "Rêves", dreams_path, class: "dropdown-item" %>
              <%= link_to "Nouveau rêve", new_dream_path, class: "dropdown-item" %>
              <%= link_to "Se déconnecter", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>

            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Se connecter", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>